#!/bin/bash
modname=ixa-pipe-pos
#
# Find the path to this module
#
if
  [ -z ${MODROOT+x} ]
then
  # Find out path ourselves
  thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
else
  thisdir=$MODROOT/$modname
fi
scriptpath=${thisdir}/run
#
# Get optional parameters (overriding environment paramers):
# -l : Lemma-model
# -m : pos-model
opts=""
while getopts l:m: opt; do
   case $opt in
     l) LEMMODEL=$OPTARG
        ;;
     m) POSMODEL=$OPTARG
        ;;
     *) echo "Unknown option." 
        exit 1
        ;;
    esac
done
#
# Set model parameters:
#
POSMODEL_DEFAULT="morph-models-1.5.0/en/en-pos-perceptron-autodict01-conll09.bin"
POSMODEL=${POSMODEL:-$POSMODEL_DEFAULT}
LEMMODEL_DEFAULT="morph-models-1.5.0/en/en-lemma-perceptron-conll09.bin"
LEMMODEL=${LEMMODEL:-$LEMMODEL_DEFAULT}
#
# Run the module
#
JARFILE=ixa-pipe-pos-1.5.2-exec.jar
cd $thisdir
java -Xmx1000m  -jar $JARFILE tag -m $thisdir/$POSMODEL -lm $thisdir/$LEMMODEL
